spring:
  profiles:
    active: fiz-dev

---

spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: fiz
    password: 314
    hikari:
      maximum-pool-size: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: fiz
    password: Fiorentina1

crg-options:
  geoserver-host: 127.0.0.1:8100
  geoserver-user: admin@mail.ru
  geoserver-password: geoserver
  exportStoragePath: /opt/export/
  userServiceName: postgres_db_user_service
