package ru.mycrg.data_service.service.cqrs.table_records.handlers;

import org.springframework.stereotype.Component;
import ru.mycrg.data_service.dao.SpatialRecordsDao;
import ru.mycrg.data_service.dao.ddl.DdlTablesSpecial;
import ru.mycrg.data_service.dao.exceptions.CrgDaoException;
import ru.mycrg.data_service.exceptions.DataServiceException;
import ru.mycrg.data_service.mappers.FeatureMapper;
import ru.mycrg.data_service.service.CustomRuleCalculator;
import ru.mycrg.data_service.service.SystemAttributeHandler;
import ru.mycrg.data_service.service.cqrs.table_records.requests.CreateTableRecordRequest;
import ru.mycrg.data_service.service.resources.ResourceQualifier;
import ru.mycrg.data_service_contract.dto.SchemaDto;
import ru.mycrg.geo_json.Feature;
import ru.mycrg.mediator.IRequestHandler;

import java.util.List;
import java.util.Map;

import static ru.mycrg.data_service.util.DetailedLogger.logError;
import static ru.mycrg.data_service.util.TableUtils.throwIfNotMatchTableColumns;

@Component
public class CreateTableRecordRequestHandler implements IRequestHandler<CreateTableRecordRequest, Feature> {

    private final CustomRuleCalculator customRuleCalculator;
    private final SystemAttributeHandler systemAttributeHandler;
    private final SpatialRecordsDao spatialRecordsDao;
    private final DdlTablesSpecial ddlTablesSpecial;

    public CreateTableRecordRequestHandler(CustomRuleCalculator customRuleCalculator,
                                           SystemAttributeHandler systemAttributeHandler,
                                           SpatialRecordsDao spatialRecordsDao,
                                           DdlTablesSpecial ddlTablesSpecial) {
        this.customRuleCalculator = customRuleCalculator;
        this.systemAttributeHandler = systemAttributeHandler;
        this.spatialRecordsDao = spatialRecordsDao;
        this.ddlTablesSpecial = ddlTablesSpecial;
    }

    @Override
    public Feature handle(CreateTableRecordRequest request) {
        Feature feature = request.getFeature();
        SchemaDto schema = request.getSchema();
        ResourceQualifier qualifier = request.getQualifier();

        List<String> allColumnNames = ddlTablesSpecial.getAllColumnNames(qualifier.getTable());
        throwIfNotMatchTableColumns(feature.getPropertyNames(),
                                    allColumnNames);

        customRuleCalculator.culculate(schema, feature.getProperties())
                            .forEach(feature::setProperty);

        Map<String, Object> modifiedProps = systemAttributeHandler
                .init(schema, feature.getProperties())
                .prepareFilesAsJsonb()
                .excludeAutoGeneratedFields()
                .decapitalize()
                .fillCreatorAndCreationDate(allColumnNames)
                .updateLastModifiedAndUpdatedBy(allColumnNames)
                .build();

        try {
            Feature newFeature = spatialRecordsDao.save(qualifier, FeatureMapper.map(feature, modifiedProps), schema);
            request.setFeature(newFeature);

            return newFeature;
        } catch (CrgDaoException e) {
            String msg = "Не удалось создать фичу в таблице: " + qualifier.getTable();
            logError(msg, e);

            throw new DataServiceException(msg);
        }
    }
}
