spring:
  profiles:
    active: fiz-dev
logging:
  file: /opt/logs/auth-service.log
  level:
    ru.mycrg: DEBUG

---

spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/gis_portal
    username: postgres
    password: 314

security:
  jwt:
    secret: vjp4lLW_QmjMHiUw1OBVRIZH
    admin_name: admin
    admin_pass: geoserver

server:
  port: 9000
