spring:
  profiles:
    active: fiz-dev
logging:
  file: /opt/logs/auth-service.log
  level:
    ru.mycrg: DEBUG

---
spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5434/crg_auth_service
    username: fiz
    password: 314
  jpa:
    show-sql: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5434/crg_auth_service
    user: fiz
    password: 314
  rabbitmq:
    host: localhost
    port: 5672
    username: fiz
    password: 314

security:
  jwt:
    secret: vjp4lLW_QmjMHiUw1OBVRIZH
    client_id: admin
    client_secret: geoserver
    access_token_validity_seconds: 86400
    refresh_token_validity_seconds: 1209600

server:
  port: 9000
