package ru.mycrg.data_service.dao.utils;

import org.geotools.data.jdbc.FilterToSQL;
import org.geotools.data.jdbc.FilterToSQLException;
import org.geotools.data.postgis.PostGISDialect;
import org.geotools.data.postgis.PostgisFilterToSQL;
import org.geotools.filter.text.cql2.CQLException;
import org.geotools.filter.text.ecql.ECQL;
import org.geotools.jdbc.AutoGeneratedPrimaryKeyColumn;
import org.geotools.jdbc.PrimaryKey;
import org.geotools.jdbc.PrimaryKeyColumn;
import org.opengis.filter.Filter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.mycrg.data_service.exceptions.BadRequestException;
import ru.mycrg.data_service_contract.dto.SimplePropertyDto;

import java.util.ArrayList;
import java.util.List;

public class EcqlHandler {

    private static final Logger log = LoggerFactory.getLogger(EcqlHandler.class);

    private EcqlHandler() {
        throw new IllegalStateException("Utility class");
    }

    public static String buildWhereSection(String ecqlFilter) {
        try {
            if (ecqlFilter == null || ecqlFilter.isBlank()) {
                return "";
            }

            Filter filter = ECQL.toFilter(ecqlFilter);
            FilterToSQL encoder = new PostgisFilterToSQL(new PostGISDialect(null));
            // encoder.setInline(true); // don't adding WHERE

            return encoder.encodeToString(filter);
        } catch (CQLException | FilterToSQLException e) {
            String msg = String.format("Задан некорректный ECQL фильтр: [%s]", ecqlFilter);
            log.error("{} Reason: [{}]", msg, e.getMessage());

            throw new BadRequestException(msg);
        }
    }

    /**
     * As example for case: Filter filter = ECQL.toFilter("IN ('river.1', 'river.2')"); From: <a
     * href="https://docs.geotools.org/latest/javadocs/org/geotools/filter/text/ecql/ECQL.html">https://docs.geotools.org/latest/javadocs/org/geotools/filter/text/ecql/ECQL.html</a>
     * <p>
     * Primary keys должны быть переданы отдельно или взяты в "".
     *
     * @return Prepared sql for WHERE
     */
    public static String buildWhereSection(String ecqlFilter, List<SimplePropertyDto> properties) {
        try {
            if (ecqlFilter == null || ecqlFilter.isBlank() || properties.isEmpty()) {
                return "";
            }

            List<PrimaryKeyColumn> columns = new ArrayList<>();
            properties.forEach(property -> {
                columns.add(new AutoGeneratedPrimaryKeyColumn(property.getName().toLowerCase(), Long.class));
            });

            Filter filter = ECQL.toFilter(ecqlFilter);
            FilterToSQL encoder = new PostgisFilterToSQL(new PostGISDialect(null));
            encoder.setPrimaryKey(new PrimaryKey("anyTableName", columns));

            return encoder.encodeToString(filter);
        } catch (CQLException | FilterToSQLException e) {
            String msg = String.format("Задан некорректный ECQL фильтр: [%s]", ecqlFilter);
            log.error("{} Reason: [{}]", msg, e.getMessage());

            throw new BadRequestException(msg);
        }
    }
}
