spring:
  profiles:
    active: fiz-dev

logging:
  file: /opt/logs/data-service.log
  level:
    ru.mycrg: DEBUG

---

server:
  port: 8084

spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5434/crg_data_service
    username: fiz
    password: 314
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

management:
  health:
    db:
      enabled: false

crg-options:
  fileStoragePath: /opt/file_storage
  geoserverDbName: geoserver_db

