spring:
  profiles:
    active: fiz-dev

logging:
  file: /opt/logs/data-service.log
  level:
    ru.mycrg: DEBUG

---

server:
  port: 8084

spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5434/crg_data_service
    username: fiz
    password: 314
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5434/crg_data_service
    user: fiz
    password: 314
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 200
  servlet:
    multipart:
      max-file-size: 1001MB
      max-request-size: 1001MB
  rabbitmq:
    host: localhost
    port: 5672
    username: fiz
    password: 314
  jackson:
    default-property-inclusion: non_null
  devtools:
    remote:
      secret: some_fiz_sercret

management:
  health:
    db:
      enabled: false

crg-options:
  auth-service-url: http://127.0.0.1:9000
  gis-service-url: http://127.0.0.1:8082
  data-service-url: http://127.0.0.1:8084
  ui-service-url: http://127.0.0.1:80
  fileStoragePath: /opt/file_storage
  geoserverDbName: geoserver_db
  exportStoragePath: /opt/export/
  client_id: admin
  client_secret: geoserver
  system-admin-login: admin@mail.ru
  system-admin-password: geoserver
  integration:
    sed-url: https://httpbin.org/anything
    gisogd-rf: https://gisogd.npc.ba/api/rgmu
    gisogd-rf-token: https://id-gisogd.npc.ba/oidc/connect/token
    gisogd-rf-client-id: gisogdrfclient1
    gisogd-rf-client-secret: XDZ8XHY8TPR2WKXR6MHPTJ0MH0V4RT9QGHZOB90D6SQG9VNA67Y2QQJ4R
    smev3:
      mnemonic: U629301
      amqp:
        host: 10.10.10.32
        username: admin
        password: admin
