spring:
  profiles:
    active: fiz-dev

logging:
  file: /opt/logs/data-service.log
  level:
    ru.mycrg: debug

---

server:
  port: 8084

spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5434/crg_data_service
    username: fiz
    password: 314
    hikari:
      minimum-pool-size: ${SPRING_DATASOURCE_HIKARI_MINIMUM_POOL_SIZE:10}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:20}
      # у data-service финальная цифра: (кол-во организаций * POOL + 1)
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5434/crg_data_service
    user: fiz
    password: 314
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 200
  servlet:
    multipart:
      max-file-size: 1001MB
      max-request-size: 1001MB
  redis:
    host: redis
    port: 6379
    password: ${SPRING_REDIS_PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: fiz
    password: 314
  jackson:
    default-property-inclusion: non_null
  devtools:
    remote:
      secret: some_fiz_sercret

management:
  health:
    db:
      enabled: false

crg-options:
  storage:
    cache:
      recordStats: true
      maximumSize: 1000
      expireAfterWrite: 30
  taskDb: database_1
  taskDeadlineTime: 5
  taskManagementFolderId: ${CRG_OPTIONS_TASK_MANAGEMENT_FOLDER_ID:29}
  kptTaskJobCron: ${CRG_OPTIONS_KPT_TASK_JOB_CRON:0 0 0 * * *}
  kptTaskDeadlineTime: ${CRG_OPTIONS_KPT_TASK_DEADLINE_TIME:720}
  auth-service-url: http://127.0.0.1:9000
  gis-service-url: http://127.0.0.1:8082
  cryptopro-service-url: http://127.0.0.1:8448
  notification-service-url: http://127.0.0.1:8668
  data-service-url: http://127.0.0.1:8084
  ui-service-url: http://127.0.0.1:80
  kptStoragePath: /opt/kpt_order/
  mainStoragePath: /opt/file_storage
  exportStoragePath: /opt/export/
  specializationsPath: /opt/crg/specializations
  geoserverDbName: geoserver_db
  client_id: admin
  client_secret: geoserver
  system-admin-login: admin@mail.ru
  system-admin-password: geoserver
  initFullTextSearch: true
  integration:
    sed-url: https://httpbin.org/anything
    gisogd-rf: https://gisogd.npc.ba/api/rgmu
    gisogd-rf-token: https://id-gisogd.npc.ba/oidc/connect/token
    gisogd-rf-client-id: gisogdrfclient1
    gisogd-rf-client-secret: XDZ8XHY8TPR2WKXR6MHPTJ0MH0V4RT9QGHZOB90D6SQG9VNA67Y2QQJ4R
    smev3:
      enabled: true
      mnemonic: U629301
      transportMnemonic: U629301
      targetDb: database_1
      s3:
        endpoint: http://smev-minio:9000
        accesskey: admin
        secretkey: oFzB?S3KFv%oFX
        bucketOutgoing: outgoing-attachments
        bucketIncoming: incoming-attachments
