version: '3.7'

services:
  rabbitmq:
    ports:
      - 5672:5672

  auth-service:
    build: auth-service
    ports:
      - 9000:9000

  gis-service:
    build: gis-service
    ports:
      - 8082:8082

  data-service:
    build: data-service
    ports:
      - 8084:8084

  geo-api:
    build: geo-api
    ports:
      - 8088:8088

  geo-wrapper:
    build: geo-wrapper

  gateway:
    build: gateway

  portal-ui:
    build: portal-ui
