version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: ${DOCKER_CRG_HOST}/rabbitmq:${RABBIT_TAG}
    restart: always
    labels:
      co.elastic.metrics/raw: "[{\"enabled\":true,\"metricsets\":[\"node\",\"queue\",\"exchange\"],\"module\":\"rabbitmq\",\"hosts\":[\"localhost:15672\"],\"username\":\"$CRG_USER\",\"password\":\"$RABBIT_PASS\"}]"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${CRG_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}

  postgis:
    container_name: postgis
    image: ${DOCKER_CRG_HOST}/postgis:${POSTGIS_TAG}
    shm_size: 1g
    labels:
      co.elastic.metrics/raw: "[{\"enabled\":true,\"metricsets\":[\"database\",\"bgwriter\",\"activity\",\"statement\"],\"module\":\"postgresql\",\"hosts\":[\"postgres://localhost:5434?sslmode=disable\"],\"username\":\"$CRG_USER\",\"password\":\"$DB_PASS\"}]"
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - /opt/data/postgis:/var/lib/postgresql
      - /opt/data/configs/db/extra.conf:/settings/extra.conf
    environment:
      POSTGRES_DBNAME: crg_auth_service,crg_gis_service,crg_data_service,geoserver_db,bpmn_camunda,crg_audit_service
      POSTGRES_USER: ${CRG_USER}
      POSTGRES_PASS: ${DB_PASS}
      RECREATE_DATADIR: ${RECREATE_DATADIR}

  geoserver:
    container_name: geoserver
    image: ${DOCKER_CRG_HOST}/geoserver:${GEOSERVER_TAG}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/geoserver || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 6
      start_period: 120s
    ports:
      - "8080:8080"
    volumes:
      - /opt/data/geoserver:/opt/geoserver/data_dir
      - /opt/gwc_storage:/opt/gwc_storage
      - /opt/spatial_data:/opt/spatial_data
      - /opt/file_storage:/opt/file_storage
    environment:
      APM_URL: ${APM_URL}
      GEOSERVER_ADMIN_USER: ${GEOSERVER_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_PASSWORD}
      INITIAL_MEMORY: ${JAVA_XMS_SIZE}
      MAXIMUM_MEMORY: ${JAVA_XMX_SIZE}
      STABLE_EXTENSIONS: importer-plugin
      COMMUNITY_EXTENSIONS: ogr-datastore-plugin


  auth-service:
    container_name: crg-auth
    image: ${DOCKER_CRG_HOST}/auth-service:${CRG_AUTH_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_auth_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_auth_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}
      CRG_OPTIONS_SYSTEM_ADMIN_LOGIN: ${SYSTEM_ADMIN_LOGIN}
      CRG_OPTIONS_SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}

      ESIA_URL: ${ESIA_URL:-https://esia.gosuslugi.ru}
      ESIA_CLIENT_ID: GISOGD_CRIMEA
      ESIA_ORG_ID: 1
      ESIA_GROUP_ID: ${ESIA_GROUP_ID:-314314}
      ESIA_KEY_STORE_PATH: /opt/key_storage/esia_store.pfx
      ESIA_KEY_STORE_PASS: ${ESIA_KEY_STORE_PASS:-314314}
      ESIA_KEY_STORE_ALIAS: ${ESIA_KEY_STORE_ALIAS:-fpy}
      ESIA_KEY_STORE_SIGN_ALG: GOST3411-2012-256WITHECGOST3410-2012-256

      SECURITY_JWT_ACCESS_TOKEN_VALIDITY_SECONDS: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS:-}
      SECURITY_JWT_REFRESH_TOKEN_VALIDITY_SECONDS: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS:-}
    volumes:
      - /opt/logs:/opt/logs
      - /opt/key_storage:/opt/key_storage
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  integration-service:
    container_name: crg-integration-service
    image: ${DOCKER_CRG_HOST}/crg-integration-service:${CRG_INTEGRATION_SERVICE_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/bpmn_camunda
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_AUDIT_SERVICE_URL: http://audit-service:8086
      CRG_OPTIONS_GEOSERVER_HOST: geoserver:8080
    ports:
      - "8338:8338"
    volumes:
      - /opt/logs:/opt/logs

  data-service:
    container_name: crg-data-service
    image: ${DOCKER_CRG_HOST}/crg-data-service:${CRG_DATA_SERVICE_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_data_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_data_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

      CRG_OPTIONS_AUTH_SERVICE_URL: http://auth-service:9000
      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_UI_SERVICE_URL: http://portal-ui:80
      CRG_OPTIONS_FILE_STORAGE_PATH: /opt/file_storage
      CRG_OPTIONS_GEOSERVER_DB_NAME: geoserver_db
      CRG_OPTIONS_EXPORT_STORAGE_PATH: /opt/export/
      CRG_OPTIONS_CLIENT_ID: admin
      CRG_OPTIONS_CLIENT_SECRET: geoserver
      CRG_OPTIONS_SYSTEM_ADMIN_LOGIN: ${SYSTEM_ADMIN_LOGIN}
      CRG_OPTIONS_SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}

      CRG_OPTIONS_INTEGRATION_SED_URL: https://sed-server/docker-config-endpoint
      CRG_OPTIONS_INTEGRATION_GISOGD_RF: https://gisogd.npc.ba/api/rgmu
      CRG_OPTIONS_INTEGRATION_GISOGD_RF_TOKEN: https://id-gisogd.npc.ba/oidc/connect/token
      CRG_OPTIONS_INTEGRATION_GISOGD_RF_CLIENT_ID: gisogdrfclient1
      CRG_OPTIONS_INTEGRATION_GISOGD_RF_CLIENT_SECRET: XDZ8XHY8TPR2WKXR6MHPTJ0MH0V4RT9QGHZOB90D6SQG9VNA67Y2QQJ4R
    volumes:
      - /opt/logs:/opt/logs
      - /opt/file_storage:/opt/file_storage
      - /opt/export:/opt/export
      - /opt/spatial_data:/opt/spatial_data
    ports:
      - "8084:8084"

  gis-service:
    container_name: crg-gis-service
    image: ${DOCKER_CRG_HOST}/crg-gis-service:${CRG_GIS_SERVICE_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_gis_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_gis_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

      CRG_OPTIONS_AUTH_SERVICE_URL: http://auth-service:9000
      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_CLIENT_ID: admin
      CRG_OPTIONS_CLIENT_SECRET: geoserver
      CRG_OPTIONS_SYSTEM_ADMIN_LOGIN: ${SYSTEM_ADMIN_LOGIN}
      CRG_OPTIONS_SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}

      CRG_OPTIONS_GEOSERVER_HOST: geoserver:8080
      CRG_OPTIONS_USER_SERVICE_NAME: postgres_db_user_service
    volumes:
      - /opt/logs:/opt/logs
    ports:
      - "8082:8082"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    container_name: crg-gateway
    image: ${DOCKER_CRG_HOST}/crg-gateway:${CRG_GATEWAY_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}
      CRG_OPTIONS_AUTH_SERVICE_URL: http://auth-service:9000
      CRG_OPTIONS_CLIENT_ID: admin
      CRG_OPTIONS_CLIENT_SECRET: geoserver

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}
    ports:
      - "8100:8100"
    volumes:
      - /opt/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  geo-wrapper:
    container_name: geo-wrapper
    image: ${DOCKER_CRG_HOST}/geo-wrapper:${CRG_WRAPPER_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_GEOSERVER_HOST: geoserver:8080
      CRG_OPTIONS_USER_SERVICE_NAME: postgres_db_user_service

      CRG_OPTIONS_EXPORT_STORAGE_PATH: /opt/export/
    depends_on:
      - rabbitmq
    volumes:
      - /opt/fgistp:/opt/fgistp
      - /opt/export:/opt/export
      - /opt/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  portal-ui:
    container_name: crg-ui
    image: ${DOCKER_CRG_HOST}/crg-ui:${CRG_UI_TAG}
    restart: always
    environment:
      UI_PLATFORM: $UI_PLATFORM
      UI_PROD: $UI_PROD
      UI_TITLE: ${UI_TITLE:-}
      UI_OWNER: ${UI_OWNER:-}
      UI_CONTACTS_PHONE: ${UI_CONTACTS_PHONE:-}
      UI_CONTACTS_EMAIL: ${UI_CONTACTS_EMAIL:-}
      UI_DESCRIPTION: ${UI_DESCRIPTION:-}
      UI_PASSWORD_RESTORE: ${UI_PASSWORD_RESTORE:-}
      UI_ESIA: ${UI_ESIA:-}
      UI_REGISTRATION: ${UI_REGISTRATION:-}
      UI_BACKGROUND: ${UI_BACKGROUND:-}
      UI_SERVER_HOST: ${UI_SERVER_HOST:-}
      UI_SERVER_PORT: ${UI_SERVER_PORT:-}
      UI_SERVER_PATH: ${UI_SERVER_PATH:-/api}
      UI_WS_PORT: ${UI_WS_PORT:-}
      UI_WS_PATH: ${UI_WS_PATH:-/ws}
      UI_SWN: $UI_SWN
      UI_LOGO: ${UI_LOGO:-}
      UI_FAVICON: ${UI_FAVICON:-}
      UI_HTTPS: ${UI_HTTPS:-}
      UI_SUPRESS_TOAST_ERRORS_HTTP: ${UI_SUPRESS_TOAST_ERRORS_HTTP:-}
      UI_SUPRESS_TOAST_ERRORS_HTTPS: ${UI_SUPRESS_TOAST_ERRORS_HTTPS:-}
      UI_SEND_ERRORS_TO_TG_HTTP: ${UI_SEND_ERRORS_TO_TG_HTTP:-}
      UI_SEND_ERRORS_TO_TG_HTTPS: ${UI_SEND_ERRORS_TO_TG_HTTPS:-}
    volumes:
      - /opt/reglaments:/usr/share/nginx/html/reglaments
      - /opt/ssl:/opt/ssl
    ports:
      - "80:80"
      - "443:443"

  audit-service:
    container_name: crg-audit-service
    image: ${DOCKER_CRG_HOST}/crg-audit-service:${CRG_AUDIT_SERVICE_TAG}
    restart: always
    environment:
      APM_URL: ${APM_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_audit_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_audit_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

    ports:
      - "8086:8086"
    volumes:
      - /opt/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
