version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: ${DOCKER_CRG_HOST}/rabbitmq:${RABBIT_TAG}
    restart: always
    labels:
      co.elastic.metrics/raw: "[{\"enabled\":true,\"metricsets\":[\"node\",\"queue\",\"exchange\"],\"module\":\"rabbitmq\",\"hosts\":[\"localhost:15672\"],\"username\":\"$CRG_USER\",\"password\":\"$RABBIT_PASS\"}]"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${CRG_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    mem_limit: ${RABBITMQ_MEM_LIMIT:-20000}m

  postgis:
    container_name: postgis
    image: ${DOCKER_CRG_HOST}/postgis:${POSTGIS_TAG}
    shm_size: ${SHM_SIZE:-2g}
    labels:
      co.elastic.metrics/raw: "[{\"enabled\":true,\"metricsets\":[\"database\",\"bgwriter\",\"activity\",\"statement\"],\"module\":\"postgresql\",\"hosts\":[\"postgres://localhost:5434/crg_auth_service?sslmode=disable\"],\"username\":\"$CRG_USER\",\"password\":\"$DB_PASS\"}]"
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - /opt/data/postgis:/var/lib/postgresql
      - /opt/data/configs/db/extra.conf:/settings/extra.conf
    environment:
      POSTGRES_DBNAME: crg_notification_db,crg_auth_service,crg_gis_service,crg_data_service,geoserver_db,bpmn_camunda,crg_audit_service,gsstore,gscatalog
      POSTGRES_USER: ${CRG_USER}
      POSTGRES_PASS: ${DB_PASS}
      RECREATE_DATADIR: ${RECREATE_DATADIR}
    mem_limit: ${POSTGIS_MEM_LIMIT:-2100}m

  geoserver:
    container_name: geoserver
    image: ${DOCKER_CRG_HOST}/geoserver:${GEOSERVER_TAG}
    restart: always
    healthcheck:
      test: curl -f http://localhost:8080/geoserver || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
    ports:
      - "8080:8080"
    volumes:
      - /opt/data/geoserver:/opt/geoserver/data_dir
      - /opt/gwc_storage:/opt/gwc_storage
      - /opt/spatial_data:/opt/spatial_data
      - /opt/file_storage:/opt/file_storage
    environment:
      APM_URL: ${APM_URL}

      INITIAL_MEMORY: ${GEOSERVER_XMS_SIZE:-20G}
      MAXIMUM_MEMORY: ${GEOSERVER_XMX_SIZE:-20G}

      GEOSERVER_ADMIN_USER: ${GEOSERVER_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_PASSWORD}
      STABLE_EXTENSIONS: importer-plugin,jp2k-plugin
      COMMUNITY_EXTENSIONS: ogr-datastore-plugin,jdbcconfig-plugin,jdbcstore-plugin

    mem_limit: ${GEOSERVER_MEM_LIMIT:-21000}m

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /opt/data/redis:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    command: redis-server --requirepass ${REDIS_PASS}
    mem_limit: ${REDIS_MEM_LIMIT:-500}m


  auth-service:
    container_name: crg-auth
    image: ${DOCKER_CRG_HOST}/auth-service:${CRG_AUTH_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${AUTH_XMX_SIZE:-1120m}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_auth_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      SPRING_DATASOURCE_HIKARI_MINIMUM_POOL_SIZE: ${HIKARI_AUTH_MINIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${HIKARI_AUTH_MAXIMUM_POOL_SIZE}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_auth_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}
      CRG_OPTIONS_SYSTEM_ADMIN_LOGIN: ${SYSTEM_ADMIN_LOGIN}
      CRG_OPTIONS_SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}

      ESIA_URL: https://esia.gosuslugi.ru
      ESIA_CLIENT_ID: GISOGD_CRIMEA
      ESIA_CLIENT_CERTIFICATE_HASH: ${ESIA_CLIENT_CERTIFICATE_HASH:-A36D6A216A23D945484AD96DE11AED862F950AC88165A6A9D1D2F8F583D6DA4C}
      ESIA_ORG_ID: 1
      ESIA_GROUP_ID: ${ESIA_GROUP_ID:-314314}
      ESIA_KEY_STORE_PATH: /opt/key_storage/esia_store.pfx
      ESIA_KEY_STORE_PASS: ${ESIA_KEY_STORE_PASS:-314314}
      ESIA_KEY_STORE_ALIAS: ${ESIA_KEY_STORE_ALIAS:-1}
      ESIA_KEY_STORE_SIGN_ALG: GOST3411-2012-256WITHECGOST3410-2012-256

      SECURITY_JWT_ACCESS_TOKEN_VALIDITY_SECONDS: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS:-}
      SECURITY_JWT_REFRESH_TOKEN_VALIDITY_SECONDS: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS:-}
    volumes:
      - /opt/logs:/opt/logs
      - /opt/key_storage:/opt/key_storage
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: ${AUTH_MEM_LIMIT:-1200}m

  integration-service:
    container_name: crg-integration-service
    image: ${DOCKER_CRG_HOST}/crg-integration-service:${CRG_INTEGRATION_SERVICE_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${INTEGRATION_XMX_SIZE:-1000m}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/bpmn_camunda
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_AUDIT_SERVICE_URL: http://audit-service:8086
      CRG_OPTIONS_AUTH_SERVICE_URL: http://auth-service:9000
      CRG_OPTIONS_CLIENT_ID: admin
      CRG_OPTIONS_CLIENT_SECRET: geoserver
      CRG_OPTIONS_GEOSERVER_HOST: geoserver:8080
    ports:
      - "8338:8338"
    volumes:
      - /opt/logs:/opt/logs
    mem_limit: ${INTEGRATION_MEM_LIMIT:-1100}m

  data-service:
    container_name: crg-data-service
    image: ${DOCKER_CRG_HOST}/crg-data-service:${CRG_DATA_SERVICE_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}
      APM_DATA_CPU: ${APM_DATA_CPU}

      XMX_SIZE: ${DATA_XMX_SIZE:-2000m}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_data_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${HIKARI_DATA_MAXIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MINIMUM_POOL_SIZE: ${HIKARI_DATA_MINIMUM_POOL_SIZE}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}
      SPRING_REDIS_PASSWORD: ${REDIS_PASS}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_data_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

      CRG_OPTIONS_TASK_DB: database_1
      CRG_OPTIONS_TASK_MANAGEMENT_FOLDER_ID: ${CRG_OPTIONS_TASK_MANAGEMENT_FOLDER_ID:-29}
      CRG_OPTIONS_TASK_DEADLINE_TIME: 5
      CRG_OPTIONS_KPT_TASK_JOB_CRON: ${CRG_OPTIONS_KPT_TASK_JOB_CRON:-0 0 0 * * *}
      CRG_OPTIONS_KPT_TASK_DEADLINE_TIME: ${CRG_OPTIONS_KPT_TASK_DEADLINE_TIME:-720}
      CRG_OPTIONS_AUTH_SERVICE_URL: http://auth-service:9000
      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_CRYPTOPRO_SERVICE_URL: http://cryptopro-service:8448
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_UI_SERVICE_URL: http://portal-ui:80
      CRG_OPTIONS_KPT_STORAGE_PATH: /opt/kpt_order/
      CRG_OPTIONS_MAIN_STORAGE_PATH: /opt/file_storage
      CRG_OPTIONS_EXPORT_STORAGE_PATH: /opt/export/
      CRG_OPTIONS_GEOSERVER_DB_NAME: geoserver_db
      CRG_OPTIONS_CLIENT_ID: admin
      CRG_OPTIONS_CLIENT_SECRET: geoserver
      CRG_OPTIONS_SYSTEM_ADMIN_LOGIN: ${SYSTEM_ADMIN_LOGIN}
      CRG_OPTIONS_SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}

      CRG_OPTIONS_INTEGRATION_SED_URL: https://sed-server/docker-config-endpoint
      CRG_OPTIONS_INTEGRATION_GISOGD_RF: https://gisogd.npc.ba/api/rgmu
      CRG_OPTIONS_INTEGRATION_GISOGD_RF_TOKEN: https://id-gisogd.npc.ba/oidc/connect/token
      CRG_OPTIONS_INTEGRATION_GISOGD_RF_CLIENT_ID: gisogdrfclient1
      CRG_OPTIONS_INTEGRATION_GISOGD_RF_CLIENT_SECRET: XDZ8XHY8TPR2WKXR6MHPTJ0MH0V4RT9QGHZOB90D6SQG9VNA67Y2QQJ4R

      CRG_OPTIONS_INTEGRATION_SMEV3_ENABLED: ${SMEV3_ENABLED:-true}
      CRG_OPTIONS_INTEGRATION_SMEV3_MNEMONIC: ${SMEV3_MNEMONIC:-U629301}
      CRG_OPTIONS_INTEGRATION_SMEV3_TRANSPORT_MNEMONIC: ${SMEV3_TRANSPORT_MNEMONIC:-U629301}
      CRG_OPTIONS_INTEGRATION_SMEV3_TARGET_DB: ${SMEV3_TARGET_DB:-database_1}
      CRG_OPTIONS_INTEGRATION_SMEV3_S3_ENDPOINT: ${SMEV3_S3_ENDPOINT:-http://10.10.10.32:9000}
      CRG_OPTIONS_INTEGRATION_SMEV3_S3_ACCESSKEY: ${SMEV3_S3_ACCESSKEY:-admin}
      CRG_OPTIONS_INTEGRATION_SMEV3_S3_SECRETKEY: ${SMEV3_S3_SECRETKEY:-oFzB?S3KFv%oFX}
    volumes:
      - /opt/logs:/opt/logs
      - /opt/file_storage:/opt/file_storage
      - /opt/export:/opt/export
      - /opt/spatial_data:/opt/spatial_data
      - /opt/kpt_order:/opt/kpt_order
      - /opt/crg/specializations:/opt/crg/specializations
    ports:
      - "8084:8084"
    mem_limit: ${DATA_MEM_LIMIT:-2100}m

  gis-service:
    container_name: crg-gis-service
    image: ${DOCKER_CRG_HOST}/crg-gis-service:${CRG_GIS_SERVICE_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${GIS_XMX_SIZE:-1640m}

      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${HIKARI_GIS_MAXIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MINIMUM_POOL_SIZE: ${HIKARI_GIS_MINIMUM_POOL_SIZE}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_gis_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_gis_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

      CRG_OPTIONS_AUTH_SERVICE_URL: http://auth-service:9000
      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_CLIENT_ID: admin
      CRG_OPTIONS_CLIENT_SECRET: geoserver
      CRG_OPTIONS_SYSTEM_ADMIN_LOGIN: ${SYSTEM_ADMIN_LOGIN}
      CRG_OPTIONS_SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}
      CRG_OPTIONS_GEOSERVER_HOST: geoserver:8080
      CRG_OPTIONS_USER_SERVICE_NAME: postgres_db_user_service
    volumes:
      - /opt/logs:/opt/logs
      - /opt/crg/specializations:/opt/crg/specializations
    ports:
      - "8082:8082"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: ${GIS_MEM_LIMIT:-1700}m

  gateway:
    container_name: crg-gateway
    image: ${DOCKER_CRG_HOST}/crg-gateway:${CRG_GATEWAY_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${GATEWAY_XMX_SIZE:-920m}

      CRG_OPTIONS_AUTH_SERVICE_URL: http://auth-service:9000
      CRG_OPTIONS_CLIENT_ID: admin
      CRG_OPTIONS_CLIENT_SECRET: geoserver

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}
    ports:
      - "8100:8100"
    volumes:
      - /opt/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: ${GATEWAY_MEM_LIMIT:-20000}m

  geo-wrapper:
    container_name: geo-wrapper
    image: ${DOCKER_CRG_HOST}/geo-wrapper:${CRG_WRAPPER_TAG}
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${WRAPPER_XMX_SIZE:-1120m}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      CRG_OPTIONS_GIS_SERVICE_URL: http://gis-service:8082
      CRG_OPTIONS_DATA_SERVICE_URL: http://data-service:8084
      CRG_OPTIONS_GEOSERVER_HOST: geoserver:8080
      CRG_OPTIONS_USER_SERVICE_NAME: postgres_db_user_service

      CRG_OPTIONS_EXPORT_STORAGE_PATH: /opt/export/
    depends_on:
      - rabbitmq
    volumes:
      - /opt/fgistp:/opt/fgistp
      - /opt/export:/opt/export
      - /opt/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: ${WRAPPER_MEM_LIMIT:-1200}m

  portal-ui:
    container_name: crg-ui
    image: ${DOCKER_CRG_HOST}/crg-ui:${CRG_UI_TAG}
    restart: always
    environment:
      UI_PLATFORM: $UI_PLATFORM
      UI_PROD: $UI_PROD
      UI_TITLE: ${UI_TITLE:-}
      UI_OWNER: ${UI_OWNER:-}
      UI_CONTACTS_PHONE: ${UI_CONTACTS_PHONE:-}
      UI_CONTACTS_EMAIL: ${UI_CONTACTS_EMAIL:-}
      UI_DESCRIPTION: ${UI_DESCRIPTION:-}
      UI_PASSWORD_RESTORE: ${UI_PASSWORD_RESTORE:-}
      UI_ESIA: ${UI_ESIA:-}
      UI_REGISTRATION: ${UI_REGISTRATION:-}
      UI_BACKGROUND: ${UI_BACKGROUND:-}
      UI_SERVER_HOST: ${UI_SERVER_HOST:-}
      UI_SERVER_PORT: ${UI_SERVER_PORT:-}
      UI_SERVER_PATH: ${UI_SERVER_PATH:-/api}
      UI_WS_PORT: ${UI_WS_PORT:-}
      UI_WS_PATH: ${UI_WS_PATH:-/ws}
      UI_SWN: $UI_SWN
      UI_LOGO: ${UI_LOGO:-}
      UI_FAVICON: ${UI_FAVICON:-}
      UI_HTTPS: ${UI_HTTPS:-}
      UI_SUPRESS_TOAST_ERRORS_HTTP: ${UI_SUPRESS_TOAST_ERRORS_HTTP:-}
      UI_SUPRESS_TOAST_ERRORS_HTTPS: ${UI_SUPRESS_TOAST_ERRORS_HTTPS:-}
      UI_SEND_ERRORS_TO_TG_HTTP: ${UI_SEND_ERRORS_TO_TG_HTTP:-}
      UI_SEND_ERRORS_TO_TG_HTTPS: ${UI_SEND_ERRORS_TO_TG_HTTPS:-}
    volumes:
      - /opt/reglaments:/usr/share/nginx/html/reglaments
      - /opt/ssl:/opt/ssl
    ports:
      - "80:80"
      - "443:443"
    mem_limit: ${UI_MEM_LIMIT:-560}m

  audit-service:
    container_name: crg-audit-service
    image: ${DOCKER_CRG_HOST}/crg-audit-service:${CRG_AUDIT_SERVICE_TAG}
    restart: always
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${AUDIT_XMX_SIZE:-1120m}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/crg_audit_service
      SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgis:5432/crg_audit_service
      SPRING_FLYWAY_USER: ${CRG_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASS}

    ports:
      - "8086:8086"
    volumes:
      - /opt/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: ${AUDIT_MEM_LIMIT:-1200}m

  gisogd-service:
    container_name: crg-gisogd-service
    image: ${DOCKER_CRG_HOST}/crg-gisogd-service:${CRG_GISOGD_SERVICE_TAG}
    restart: always
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${GISOGD_XMX_SIZE:-620m}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${CRG_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GISOGDRFCLIENT_CLIENT-ID: ${GISOGDRF_CLIENT}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GISOGDRFCLIENT_CLIENT-SECRET: ${GISOGDRF_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GISOGDRFCLIENT_TOKEN-URI: ${GISOGDRF_TOKEN_URI}
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_GISOGDRFCLIENT_URL: ${GISOGDRF_URL}
      CAMEL_GET-REQUESTED-DOCUMENTS_SCHEDULE: ${GISOGD_GET_DOCUMENTS_LIST_CRON:-0 0 * * * ?}
    ports:
      - "8088:8088"
    volumes:
      - /opt/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: ${GISOGD_MEM_LIMIT:-650}m

  cryptopro-service:
    container_name: crg-cryptopro-service
    image: ${DOCKER_CRG_HOST}/crg-cryptopro:5.2
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    volumes:
      - /opt/logs:/opt/logs
      - /opt/file_storage:/opt/file_storage
    ports:
      - "8448:8448"
    mem_limit: ${CRYPTOPRO_MEM_LIMIT:-400}m
    privileged: true

  notification-service:
    container_name: crg-notification-service
    image: ${DOCKER_CRG_HOST}/crg-notification-service:latest
    restart: always
    extra_hosts:
      - "logstash:${LOGSTASH_HOST}"
    volumes:
      - /opt/logs:/opt/logs
      - /opt/file_storage:/opt/file_storage
    ports:
      - "8668:8668"
    mem_limit: ${CRYPTOPRO_MEM_LIMIT:-400}m
