version: '3.7'

services:
  rabbitmq:
    ports:
      - 5672:5672

  auth-service:
    build: auth-service
    ports:
      - 9000:9000

  gis-service:
    build: gis-service

  geo-api:
    build: geo-api
    ports:
      - 8088:8088

  geo-wrapper:
    build: geo-wrapper

  gateway:
    build: gateway

  portal-ui:
    build: portal-ui
