version: '3.7'

services:
  gisogd-service:
    container_name: crg-gisogd-service
    image: ${DOCKER_CRG_HOST}/crg-gisogd-service:1.0
    restart: always
    environment:
      APM_URL: ${APM_URL}

      XMX_SIZE: ${GISOGD_XMX_SIZE:-620m}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DATASERVICECLIENT_CLIENT-ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DATASERVICECLIENT_CLIENT_ID:-test@mail.ru}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DATASERVICECLIENT_CLIENT-SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DATASERVICECLIENT_CLIENT_SECRET:-test}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GISOGDRFCLIENT_CLIENT-ID: ${GISOGDRF_CLIENT:-prodkrym}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GISOGDRFCLIENT_CLIENT-SECRET: ${GISOGDRF_SECRET:-testHashString}

      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GISOGDRFCLIENT_TOKEN-URI: ${GISOGDRF_TOKEN_URI:-https://id.gisogd.gov.ru/oidc/connect/token}
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_GISOGDRFCLIENT_URL: ${GISOGDRF_URL:-https://admin.gisogd.gov.ru/api/rgmu/}
      CAMEL_GET-REQUESTED-DOCUMENTS_SCHEDULE: ${GISOGD_GET_DOCUMENTS_LIST_CRON:-0 0 * * * ?}
    ports:
      - "8088:8088"
    volumes:
      - ${CRG_DATA_DIR:-/opt/crg}/logs:/opt/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: ${GISOGD_MEM_LIMIT:-650}m
    privileged: true
