version: '3.7'
services:
  gisogd-integration-sed-service:
    container_name: gisogd-integration-sed-service
    image: ${DOCKER_CRG_HOST}/gisogd-integration-sed-service:1.0
    restart: always
    environment:
      # APM Configuration
      APM_URL: ${APM_URL:-10.10.10.124}
      XMX_SIZE: ${GISOGD_INTEGRAION_XMX_SIZE:-2000m}

      # Logging Configuration
      GISOGD_INTEGRAION_LOG_LEVEL: ${GISOGD_INTEGRAION_LOG_LEVEL:-debug}

      # Server Configuration
      GISOGD_INTEGRAION_SERVER_PORT: ${GISOGD_INTEGRAION_SERVER_PORT:-8888}

      # Spring Configuration
      GISOGD_INTEGRAION_SPRING_PROFILES_ACTIVE: ${GISOGD_INTEGRAION_SPRING_PROFILES_ACTIVE:-fiz-dev}

      # Database Configuration
      GISOGD_INTEGRAION_SPRING_DATASOURCE_URL: ${GISOGD_INTEGRAION_SPRING_DATASOURCE_URL:-jdbc:postgresql://postgis:5432/database_1?currentSchema=data}
      GISOGD_INTEGRAION_SPRING_DATASOURCE_USERNAME: ${CRG_USER}
      GISOGD_INTEGRAION_SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      GISOGD_INTEGRAION_SPRING_HIKARI_MAXIMUM_POOL_SIZE: ${GISOGD_INTEGRAION_SPRING_HIKARI_MAXIMUM_POOL_SIZE:-20}

      # CRG SED Options
      GISOGD_INTEGRAION_CRG_OPTIONS_SED_TRASH_FOLDER_ID: ${GISOGD_INTEGRAION_CRG_OPTIONS_SED_TRASH_FOLDER_ID:-5}
      GISOGD_INTEGRAION_CRG_OPTIONS_SED_MAIN_BOSS_ID: ${GISOGD_INTEGRAION_CRG_OPTIONS_SED_MAIN_BOSS_ID:-2}
      GISOGD_INTEGRAION_CRG_OPTIONS_SED_SERVER_IP: ${GISOGD_INTEGRAION_CRG_OPTIONS_SED_SERVER_IP:-10.0.133.101}
      GISOGD_INTEGRAION_CRG_OPTIONS_SED_CLIENT_ID: ${GISOGD_INTEGRAION_CRG_OPTIONS_SED_CLIENT_ID:-клиентID}
      GISOGD_INTEGRAION_CRG_OPTIONS_SED_SECRET: ${GISOGD_INTEGRAION_CRG_OPTIONS_SED_SECRET:-секретныйСекрет}

    volumes:
      - ${CRG_DATA_DIR:-/opt/crg}/logs:/opt/logs
    ports:
      - "${SERVER_PORT:-8888}:${SERVER_PORT:-8888}"
    mem_limit: ${GISOGD_INTEGRAION_MEM_LIMIT:-2100}m
    privileged: true
