version: '3.7'

services:
  maintenance:
    restart: unless-stopped
    image: ${DOCKER_CRG_HOST}/maintenance:latest
    container_name: maintenance
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTPS_ALLOWED=${HTTPS_ALLOWED:-0}
      - MAINTENANCE_TIME=${MAINTENANCE_TIME:-Планируемое время работ 10 минут.}
    volumes:
      - /opt/crg/ssl:/opt/crg/ssl
