#!/bin/sh
# shellcheck source=./_/husky.sh
HUSKY_ROOT="$(dirname "$0")"
. "$HUSKY_ROOT/_/husky.sh"

#cd ../scripts || exit
#./build-and-copy-generated-types.sh

REPO_ROOT="$(dirname "$HUSKY_ROOT")"
cd "$REPO_ROOT/portal-ui" || exit
lint-staged
cd portal-ui && lint-staged
