spring:
  profiles:
    active: fiz-dev
logging:
  file: /opt/crg/logs/audit-service.log
  level:
    ru.mycrg: DEBUG

---
spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}

server:
  port: 8086
