#
initdb=true
import=true
enabled=true
pool.timeBetweenEvictionRunsMillis=-1L
pool.poolPreparedStatements=true
pool.testWhileIdle=false
pool.validationQuery=SELECT now()
pool.minIdle=4
pool.maxOpenPreparedStatements=50
pool.maxActive=10
pool.testOnBorrow=true
jdbcUrl=jdbc:postgresql://10.10.10.168:5434/gsstore
driverClassName=org.postgresql.Driver
initScript=jdbcstore/scripts/init.postgres.sql
username=fiz
password=314

ignoreDirs=data,jdbcstore,jdbcconfig,temp,tmp,logs
deleteDestinationOnRename=true
