package ru.mycrg.data_service.util;

import org.jetbrains.annotations.NotNull;
import ru.mycrg.data_service_contract.dto.SchemaDto;
import ru.mycrg.data_service_contract.dto.SimplePropertyDto;
import ru.mycrg.data_service_contract.dto.ValueTitleProjection;
import ru.mycrg.data_service_contract.enums.ValueType;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Predicate;
import java.util.stream.Collectors;

import static java.util.Objects.isNull;
import static java.util.Objects.nonNull;
import static ru.mycrg.data_service_contract.enums.ValueType.*;

public class SchemaUtil {

    private static final List<ValueType> typesReadyForFts = List.of(STRING, DATETIME, DOCUMENT, CHOICE, FILE, FIAS,
                                                                    LOOKUP, UUID, USER, TEXT, URL);

    private SchemaUtil() {
        throw new IllegalStateException("Utility class");
    }

    public static boolean isPropertyExist(SchemaDto schema, String key) {
        return schema.getProperties().stream()
                     .anyMatch(property -> property.getName().equalsIgnoreCase(key));
    }

    public static boolean isFilePropertyExist(SchemaDto schema) {
        return isPropertyExistByType(schema, FILE);
    }

    public static String getEnumerationTitleByValue(SimplePropertyDto property, String value) {
        return property
                .getEnumerations().stream()
                .filter(en -> en.getValue().equals(value))
                .findFirst()
                .map(ValueTitleProjection::getTitle)
                .orElse(value);
    }

    public static Optional<String> getPropertyNameByType(ValueType type, List<SimplePropertyDto> properties) {
        return properties.stream()
                         .filter(simplePropertyDto -> simplePropertyDto.getValueTypeAsEnum().equals(type))
                         .map(SimplePropertyDto::getName)
                         .findFirst();
    }

    public static List<String> getFtsProperties(SchemaDto schema) {
        return schema.getProperties().stream()
                     .filter(SchemaUtil::isSearchable)
                     .map(SimplePropertyDto::getName)
                     .collect(Collectors.toList());
    }

    public static Optional<SimplePropertyDto> getPropertyByName(SchemaDto schema, String name) {
        return schema
                .getProperties().stream()
                .filter(prDto -> prDto.getName().equalsIgnoreCase(name))
                .findFirst();
    }

    public static boolean isComplexField(List<SimplePropertyDto> properties, String propertyName) {
        return properties.stream()
                         .filter(property -> property.getName().equalsIgnoreCase(propertyName))
                         .anyMatch(property -> FILE.equals(property.getValueTypeAsEnum()));
    }

    public static Map<String, String> getPropertiesWithCalculatedFunctions(SchemaDto schema) {
        Map<String, String> propsWithFunctions = new HashMap<>();
        schema.getProperties().forEach(simplePropertyDto -> {
            if (nonNull(simplePropertyDto.getCalculatedValueFormula())) {
                propsWithFunctions.put(simplePropertyDto.getName().toLowerCase(),
                                       simplePropertyDto.getCalculatedValueFormula());
            }
        });

        return propsWithFunctions;
    }

    public static boolean isAutogenerated(List<SimplePropertyDto> properties, String propName) {
        return properties.stream()
                         .filter(equalByName(propName))
                         .anyMatch(isGeneratedProperty());
    }

    @NotNull
    public static Predicate<SimplePropertyDto> notGeneratedProperty() {
        return prop -> {
            String formula = prop.getCalculatedValueWellKnownFormula();

            return isNull(formula) || formula.isEmpty();
        };
    }

    @NotNull
    public static Predicate<SimplePropertyDto> equalByName(String sourceName) {
        return targetProperty -> targetProperty.getName().equalsIgnoreCase(sourceName);
    }

    public static boolean isNotAutogenerated(List<SimplePropertyDto> properties, String propName) {
        return !isAutogenerated(properties, propName);
    }

    @NotNull
    public static Predicate<SimplePropertyDto> compatibleByType(ValueType sourceValueType) {
        return prop -> {
            ValueType targetType = prop.getValueTypeAsEnum();
            if (targetType.equals(STRING)) {
                return true;
            }

            if (sourceValueType.equals(STRING) && targetType.equals(CHOICE)) {
                return true;
            }

            return targetType.equals(sourceValueType);
        };
    }

    @NotNull
    private static Predicate<SimplePropertyDto> isGeneratedProperty() {
        return notGeneratedProperty().negate();
    }

    private static boolean isPropertyExistByType(SchemaDto schema, ValueType type) {
        return schema.getProperties().stream()
                     .anyMatch(property -> property.getValueTypeAsEnum().equals(type));
    }

    private static boolean isSearchable(SimplePropertyDto prop) {
        return typesReadyForFts.contains(ValueType.valueOf(prop.getValueType()));
    }
}
