package ru.mycrg.data_service.util;

import ru.mycrg.data_service_contract.dto.SchemaDto;
import ru.mycrg.data_service_contract.dto.SimplePropertyDto;
import ru.mycrg.data_service_contract.dto.ValueTitleProjection;
import ru.mycrg.data_service_contract.enums.ValueType;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static java.util.Objects.nonNull;
import static ru.mycrg.data_service_contract.enums.ValueType.FILE;

public class SchemaUtil {

    private SchemaUtil() {
        throw new IllegalStateException("Utility class");
    }

    public static boolean isPropertyExist(SchemaDto schema, String key) {
        return schema.getProperties().stream()
                     .anyMatch(property -> property.getName().equalsIgnoreCase(key));
    }

    public static boolean isFilePropertyExist(SchemaDto schema) {
        return isPropertyExistByType(schema, FILE);
    }

    public static String getEnumerationTitleByValue(SimplePropertyDto property, String value) {
        return property
                .getEnumerations().stream()
                .filter(en -> en.getValue().equals(value))
                .findFirst()
                .map(ValueTitleProjection::getTitle)
                .orElse(value);
    }

    public static Optional<String> getPropertyNameByType(ValueType type, List<SimplePropertyDto> properties) {
        return properties.stream()
                         .filter(simplePropertyDto -> simplePropertyDto.getValueTypeAsEnum().equals(type))
                         .map(SimplePropertyDto::getName)
                         .findFirst();
    }

    public static Optional<SimplePropertyDto> getPropertyByName(SchemaDto schema, String name) {
        return schema
                .getProperties().stream()
                .filter(prDto -> prDto.getName().equalsIgnoreCase(name))
                .findFirst();
    }

    public static boolean isComplexField(List<SimplePropertyDto> properties, String propertyName) {
        return properties.stream()
                         .filter(property -> property.getName().equalsIgnoreCase(propertyName))
                         .anyMatch(property -> FILE.equals(property.getValueTypeAsEnum()));
    }

    public static Map<String, String> getPropertiesWithCalculatedFunctions(SchemaDto schema) {
        Map<String, String> propsWithFunctions = new HashMap<>();
        schema.getProperties().forEach(simplePropertyDto -> {
            if (nonNull(simplePropertyDto.getCalculatedValueFormula())) {
                propsWithFunctions.put(simplePropertyDto.getName().toLowerCase(),
                                       simplePropertyDto.getCalculatedValueFormula());
            }
        });

        return propsWithFunctions;
    }

    public static boolean isAutogenerated(List<SimplePropertyDto> properties, String propName) {
        return properties.stream()
                         .filter(property -> property.getName().equalsIgnoreCase(propName))
                         .anyMatch(property -> nonNull(property.getCalculatedValueWellKnownFormula()) &&
                                 !property.getCalculatedValueWellKnownFormula().isEmpty());
    }

    public static boolean isNotAutogenerated(List<SimplePropertyDto> properties, String propName) {
        return !isAutogenerated(properties, propName);
    }

    private static boolean isPropertyExistByType(SchemaDto schema, ValueType type) {
        return schema.getProperties().stream()
                     .anyMatch(property -> property.getValueTypeAsEnum().equals(type));
    }
}
