spring:
  profiles:
    active: fiz-dev
logging:
  file: /opt/logs/gateway.log
  level:
    ru.mycrg: DEBUG

---

spring:
  profiles: fiz-dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  #  prefix: /api
  #  include-debug-header: true
  ignoredServices: '*'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    # AUTH SERVICE
    crg-auth-service:
      path: /oauth/token/**
      service-id: http://auth-service:9000/oauth/token

    crg-auth-service-groups:
      path: /groups/**
      url: http://auth-service:9000/groups/

    crg-auth-service-users:
      path: /users/**
      url: http://auth-service:9000/users/

    crg-auth-service-roles:
      path: /roles/**
      url: http://auth-service:9000/roles/

    crg-auth-service-organizations:
      path: /organizations/**
      url: http://auth-service:9000/organizations/

    # GIS SERVICE
    crg-gis-service-projects:
      path: /projects/**
      url: http://crg-gis-service:8082/projects/

    # DATA SERVICE
    crg-data-service-projects:
      path: /api/data/**
      url: http://crg-data-service:8084/

    # API SERVICE
    api-common:
      path: /api/**
      url: http://geo-api:8088/api/

    gis-processes:
      path: /processes/**
      url: http://geo-api:8088/processes/

    gis-schema:
      path: /schema/**
      url: http://geo-api:8088/schema/

    gis-export:
      path: /export/**
      url: http://geo-api:8088/export/

    gis-import:
      path: /import/**
      url: http://geo-api:8088/import/

    gis-ws:
      path: /crg-ws-endpoint/**
      url: http://geo-api:8088/crg-ws-endpoint/

    # Geoserver
    geoserver:
      path: /geoserver/**
      serviceId: http://geoserver:8080/geoserver/

server:
  port: 8100
