spring:
  profiles:
    active: fiz-dev
logging:
  file: /opt/logs/gateway.log
  level:
    ru.mycrg: DEBUG

---

spring:
  profiles: fiz-dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  #  prefix: /api
  #  include-debug-header: true
  ignoredServices: '*'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    auth-service:
      path: /oauth/token/**
      service-id: http://auth-service:9000/oauth/token

    gis-users:
      path: /users/**
      url: http://auth-service:9000/users/

    gis-organizations:
      path: /organizations/**
      url: http://geo-api:8088/organizations/

    gis-processes:
      path: /processes/**
      url: http://geo-api:8088/processes/

    gis-projects:
      path: /projects/**
      url: http://geo-api:8088/projects/

    gis-schema:
      path: /schema/**
      url: http://geo-api:8088/schema/

    gis-export:
      path: /export/**
      url: http://geo-api:8088/export/

    gis-import:
      path: /import/**
      url: http://geo-api:8088/import/

    gis-ws:
      path: /crg-ws-endpoint/**
      url: http://geo-api:8088/crg-ws-endpoint/

    # Geoserver
    geoserver:
      path: /geoserver/**
      serviceId: http://geoserver:8080/geoserver/

server:
  port: 8100
