#
initdb=true
import=true
enabled=true
pool.timeBetweenEvictionRunsMillis=-1L
pool.poolPreparedStatements=true
pool.testWhileIdle=false
pool.validationQuery=SELECT now()
pool.minIdle=4
pool.maxOpenPreparedStatements=50
pool.maxActive=10
pool.testOnBorrow=true
jdbcUrl=jdbc:postgresql://postgis:5432/gscatalog
driverClassName=org.postgresql.Driver
initScript=jdbcconfig/scripts/initdb.postgres.sql
username=fiz
password=314
