#
#Fri Apr 05 08:28:01 GMT 2024
initdb=false
pool.timeBetweenEvictionRunsMillis=-1L
deleteDestinationOnRename=true
import=false
pool.poolPreparedStatements=true
pool.testWhileIdle=false
pool.validationQuery=SELECT now()
pool.minIdle=4
ignoreDirs=data,jdbcstore,jdbcconfig,temp,tmp,logs
enabled=true
pool.maxOpenPreparedStatements=50
password=314
jdbcUrl=jdbc\:postgresql\://10.10.10.98\:5434/gsstore
driverClassName=org.postgresql.Driver
pool.maxActive=10
initScript=jdbcstore/scripts/init.postgres.sql
pool.testOnBorrow=true
username=postgres
