Feature: Регистрация новой организации

  Scenario: Успешное создание организации
    When Пользователь вводит корректные данные
      | ООО БыкиИКоровы | 1234567890 | Иванов | Иван | test@email.ru | testPassword1 |
    Then Сервер отвечает статус-кодом 202

#  Scenario: Отправка повторных данных для регистрации предприятия
#    When Пользователь посылает POST запрос на endpoint register с повторными данными
#      | testOrg | 1234567890 | testSurname | testName | email12@email.com | testtestQ1 |
#    Then Сервер отвечает со статус-кодом 409
#
#  Scenario: Отправка невалидных данных для регистрации предприятия
#    When Пользователь посылает POST запрос на endpoint register с невалидными данными
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 123456789             | testName                                                 | testSurname                                                                                                    | email                                                             | testtestQ1 | Невалидный email                   |
#      | te                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | 1234567890            | testName                                                 | testSurname                                                                                                    | email                                                             | testtestQ1 | Короткое название организации      |
#      | testOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrgtestOrg | 1234567890            | testName                                                 | testSurname                                                                                                    | email@email.com                                                   | testtestQ1 | Длинное название организации       |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 123456789012345678901 | testName                                                 | testSurname                                                                                                    | email@email.com                                                   | testtestQ1 | Длинный номер телефона организации |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            |                                                          | testSurname                                                                                                    | email@email.com                                                   | testtestQ1 | Пустое имя админа                  |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            | tes                                                      | testSurname                                                                                                    | email@email.com                                                   | testtestQ1 | Короткое имя админа                |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            | testNametestNametestNametestNametestNametestNametestName | testSurname                                                                                                    | email@email.com                                                   | testtestQ1 | Длинное имя админа                 |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            | testName                                                 |                                                                                                                | email@email.com                                                   | testtestQ1 | Пустая фамилия админа              |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            | testName                                                 | testSurnametestSurnametestSurnametestSurnametestSurnametestSurnametestSurnametestSurnametestSurnametestSurname | email@email.com                                                   | testtestQ1 | Длинная фамилия админа             |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            | testName                                                 | testSurname                                                                                                    |                                                                   | testtestQ1 | Нет email админа                   |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            | testName                                                 | testSurname                                                                                                    | emailemailemailemailemailemailemailemailemailemailemail@email.com | testtestQ1 | Длинный email админа               |
#      | testOrg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1234567890            | testName                                                 | testSurname                                                                                                    | email@email.com                                                   | testtest   | Простой пароль                     |
#    Then Сервер отвечает со статус-кодом 400
