server:
  port: 8088

spring:
  data:
    rest:
      # Only repositories annotated with @Repository are exposed, unless their exported flag is set to false.
      detection-strategy: annotated
  datasource:
    platform: postgres
#    url: jdbc:postgresql://127.0.0.1:5432/gis_portal
    username: postgres
    password: 314
  jpa:
    # show-sql: true
#    hibernate:
#      ddl-auto: update
    properties:
      # hibernate.format_sql: true
      # Fix Postgres JPA Error:
      # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.temp.use_jdbc_metadata_defaults: false
  rabbitmq:
#    host: localhost
    port: 5672
  flyway:
    enabled: true
#    url: jdbc:postgresql://127.0.0.1:5432/gis_portal
    user: postgres
    password: 314
