spring:
  profiles:
    active: fiz-dev
logging:
  file: /opt/logs/api.log
  level:
    ru.mycrg: DEBUG

---

spring:
  profiles: fiz-dev
  data:
    rest:
      detection-strategy: annotated
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/gis_portal
    username: postgres
    password: 314
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5432/gis_portal
    user: postgres
    password: 314
  rabbitmq:
    host: localhost
    port: 5672
    username: fiz
    password: Fiorentina1

server:
  port: 8088

crg-options:
  exportStoragePath: /opt/export/
  gisDbUrl: jdbc:postgresql://127.0.0.1:5434/
  gisDbUser: fiz
  gisDbPassword: 314
