#!/usr/bin/env bash

echo Init default variables
export DOCKER_CRG_HOST=${DOCKER_CRG_HOST:-cr.yandex/crp7o80lcrqlf17up9fq}

export JAVA_XMS_SIZE=${JAVA_XMS_SIZE:-2G}
export JAVA_XMX_SIZE=${JAVA_XMX_SIZE:-4G}

export APM_URL=${APM_URL:-10.10.10.10}

export CRG_USER=${CRG_USER:-fiz}
export RABBIT_PASS=${RABBIT_PASS:-314}
export DB_PASS=${DB_PASS:-314}
export GEOSERVER_USER=${GEOSERVER_USER:-admin@mail.ru}
export GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD:-geoserver}

export RABBIT_TAG=${RABBIT_TAG:-management}
export POSTGIS_TAG=${POSTGIS_TAG:-14.3-3.2}
export GEOSERVER_TAG=${GEOSERVER_TAG:-2.21.1}

export CRG_AUDIT_SERVICE_TAG=${CRG_AUDIT_SERVICE_TAG:-latest}
export CRG_INTEGRATION_SERVICE_TAG=${CRG_INTEGRATION_SERVICE_TAG:-latest}
export CRG_DATA_SERVICE_TAG=${CRG_DATA_SERVICE_TAG:-latest}
export CRG_REGISTRY_TAG=${CRG_REGISTRY_TAG:-latest}
export CRG_AUTH_TAG=${CRG_AUTH_TAG:-latest}
export CRG_GIS_SERVICE_TAG=${CRG_GIS_SERVICE_TAG:-latest}
export CRG_GATEWAY_TAG=${CRG_GATEWAY_TAG:-latest}
export CRG_API_TAG=${CRG_API_TAG:-latest}
export CRG_WRAPPER_TAG=${CRG_WRAPPER_TAG:-latest}
export CRG_UI_TAG=${CRG_UI_TAG:-latest}

export ELK_IMAGE_TAG=${ELK_IMAGE_TAG:-7.4.2}
export ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeFiz}
export ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
export ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-10.10.10.186}
export KIBANA_HOST=${KIBANA_HOST:-10.10.10.186}
export LOGSTASH_HOST=${LOGSTASH_HOST:-10.10.10.186}

export UI_PLATFORM=${UI_PLATFORM:-conv}
export UI_PROD=${UI_PROD:-false}
export UI_SERVER_HOST=${UI_SERVER_HOST:-}
export UI_SERVER_PORT=${UI_SERVER_PORT:-}
export UI_SERVER_PATH=${UI_SERVER_PATH:-}
export UI_WS_PORT=${UI_WS_PORT:-}
export UI_WS_PATH=${UI_WS_PATH:-}
export UI_SWN=${UI_SWN:-scratch_database}

export RECREATE_DATADIR=False

echo The host is: "$DOCKER_CRG_HOST"
