<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.mycrg</groupId>
    <artifactId>acceptance-tests</artifactId>
    <version>1.2-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>acceptance-tests</name>
    <description>Acceptance tests</description>

    <properties>
        <java.version>11</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <junit.version>4.13</junit.version>
        <cucumber.version>6.6.0</cucumber.version>
        <maven.compiler.version>3.8.1</maven.compiler.version>
        <maven.surefire.version>2.22.2</maven.surefire.version>
        <jackson.version>2.12.0</jackson.version>

        <skipAcceptanceTests>true</skipAcceptanceTests>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>4.3.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <!-- CRG -->
        <dependency>
            <groupId>ru.mycrg</groupId>
            <artifactId>auth-service-contract</artifactId>
            <version>1.6-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>GisPlatformFeed</id>
            <name>Gis portal azure repository</name>
            <url>https://pkgs.dev.azure.com/programgeoplan/a6547131-6a32-454f-a123-0f76fe536a3c/_packaging/GisPlatformFeed/maven/v1</url>
        </repository>
    </distributionManagement>
    <repositories>
        <repository>
            <id>GisPlatformFeed</id>
            <url>https://pkgs.dev.azure.com/programgeoplan/a6547131-6a32-454f-a123-0f76fe536a3c/_packaging/GisPlatformFeed/maven/v1</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <skipTests>${skipAcceptanceTests}</skipTests>
                    <systemPropertyVariables>
                        <!--suppress UnresolvedMavenProperty -->
                        <environment>${env.HOST}</environment>
                        <!--suppress UnresolvedMavenProperty -->
                        <environment>${env.PORT}</environment>
                        <!--suppress UnresolvedMavenProperty -->
                        <environment>${env.ROOT_NAME}</environment>
                        <!--suppress UnresolvedMavenProperty -->
                        <environment>${env.ROOT_PASS}</environment>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
