spring:
  profiles:
    active: fiz-dev

logging:
  file: /opt/logs/integration-service.log
  level:
    ru.mycrg: DEBUG

---

server:
  port: 8338

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5434/bpmn_camunda
    username: fiz
    password: 314
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: fiz
    password: 314

camunda.bpm:
  admin-user:
    id: demo
    password: demo

management:
  endpoint:
    loggers:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: loggers, health

crg-options:
  gis_service_url: http://127.0.0.1:8082
  data_service_url: http://127.0.0.1:8084
  audit_service_url: http://127.0.0.1:8086
  resources_query_base_path: "resources"
  resource_analyzers_base_path: "resource-analyzers"
