spring:
  profiles:
    active: fiz-dez

  rabbitmq:
    username: fiz
    password: 314
    host: localhost
    exchanges:
      exchange-receive-data:
        name: dataToGisogdQueue
      exchange-send-data:
        name: gisogdToDataQueue
    queues:
      queue-receive-data:
        name: dataToGisogdQueue
      queue-send-data:
        name: gisogdToDataQueue
    bindings:
      binding-receive-data:
        exchange: exchange-receive-data
        queue: queue-receive-data

  security:
    oauth2:
      client:
        registration:
          gisogdRfClient:
            client-id: preprodkrym
            client-secret: TBKJFJJ3MQH0JFIDJFX7K7WWROIP96H76IEMU8FPAV7S87ISPX7AR5LOK
            authorization-grant-type: client_credentials
        provider:
          gisogdRfClient:
            token-uri: https://test-id.gisogd.gov.ru/oidc/connect/token

  cloud:
    openfeign:
      client:
        config:
          gisogdRfClient:
            url: https://test.gisogd.gov.ru/api/rgmu/
          crimeaClient:
            url: http://data-service:8084
      oauth2:
        enabled: true
        clientRegistrationId: gisogdRfClient

logging:
  level:
    ru.mycrg: DEBUG
  file:
    name: /opt/logs/gisogd-service.log

camel:
  springboot:
    global-options:
      CamelJacksonEnableTypeConverter: true
      CamelJacksonTypeConverterToPojo: true

---

server:
  port: 8088
