spring:
  profiles:
    active: fiz-dez

  rabbitmq:
    username: fiz
    password: 314
    host: localhost
    exchanges:
      exchange-receive-data:
        name: gisogdPublicationQueue
      exchange-send-data:
        name: gisogdPublicationResponseQueue
      exchange-receive-audit-data:
        name: gisogdAuditQueue
      exchange-send-audit-response-data:
        name: gisogdAuditResponseQueue
    queues:
      queue-receive-data:
        name: gisogdPublicationQueue
      queue-send-data:
        name: gisogdPublicationResponseQueue
      queue-receive-audit-data:
        name: gisogdAuditQueue
      queue-send-audit-response-data:
        name: gisogdAuditResponseQueue
    bindings:
      binding-receive-data:
        exchange: exchange-receive-data
        queue: queue-receive-data
      binding-receive-audit-data:
        exchange: exchange-receive-audit-data
        queue: queue-receive-audit-data

  security:
    oauth2:
      client:
        registration:
          dataServiceClient:
            client-id: arh_grad_rk@mail.ru
            client-secret: Fiorentina12
            authorization-grant-type: password
            provider: dataServiceClient
          gisogdRfClient:
            client-id: preprodkrym
            client-secret: TBKJFJJ3MQH0JFIDJFX7K7WWROIP96H76IEMU8FPAV7S87ISPX7AR5LOK
            authorization-grant-type: client_credentials
            provider: gisogdRfClient
        provider:
          dataServiceClient:
            token-uri: http://crg-gateway:8100/oauth/token
          gisogdRfClient:
            token-uri: https://test-id.gisogd.gov.ru/oidc/connect/token

  cloud:
    openfeign:
      client:
        config:
          gisogdRfClient:
            url: https://test.gisogd.gov.ru/api/rgmu/
            loggerLevel: full

          dataServiceClient:
            url: http://data-service:8084
            loggerLevel: full

      oauth2:
        enabled: true

feign:
  okhttp:
    enabled: true

logging:
  level:
    ru.mycrg: DEBUG
  file:
    name: /opt/crg/logs/gisogd-service.log

camel:
  springboot:
    global-options:
      CamelJacksonEnableTypeConverter: true
      CamelJacksonTypeConverterToPojo: true

---

server:
  port: 8088
